// src/components/App.vue
<script setup lang="ts">
import { ref, reactive, onMounted, onBeforeUnmount, onUpdated, computed } from 'vue'
import mlrdLogo from "../assets/favicon.png";
import { DuckType } from '../services/duck';
import Spinner from "./Spinner.vue";
import duckService from "../services/duck";
import { cleanse as cleanseSrv } from "../services/instance";
import DuckList from './DuckList.vue';

let renderCount = ref<number>(0)

let state = reactive<{
  ducks: Record<string, DuckType>;
  numberOfOperations: number;
  isInitialized: boolean;
}>({
  numberOfOperations: 0,
  ducks: {},
  isInitialized: false
})

const isGood = (duck: DuckType) => {
  if (duck.relatedToCEO) {
    return true;
  }

  return duck.age < 8 && duck.age >= 1 && !duck.migratesForWinters;
};


const badDucks = computed(() => {
  return Object.values(state.ducks).filter(d => !isGood(d))
})

const goodDucks = computed(() => {
  return Object.values(state.ducks).filter(isGood)
})

const cleanse = async () => {
  console.log('CLEANSING')
  await cleanseSrv()
  console.log('CLEANSED!')
}

const fireDuck = async (id: string) => {
  state.ducks[id].isBeingFired = true
  state.numberOfOperations = state.numberOfOperations + 1
  await duckService.fireDuck(id)
  state.numberOfOperations = state.numberOfOperations - 1
  delete state.ducks[id]
}

let interval: number | undefined

onMounted(() => {
  interval = setInterval(() => {
    renderCount.value = renderCount.value + 1;
  }, 1000);

});

onMounted(async () => {

  state.numberOfOperations = state.numberOfOperations + 1;
  const ret = await duckService.getDucks()
  state.numberOfOperations = state.numberOfOperations - 1;
  state.ducks = Object.fromEntries(ret.map(d => [d.id, d]))
  state.isInitialized = true
});

onBeforeUnmount(() => {
  clearInterval(interval);
})

</script>

<template>
  <header>
    <h1>
      <img width="50" alt="Mallard ERP" v-bind:src="mlrdLogo" />Mallard ERP
    </h1>
    <Spinner v-if="state.numberOfOperations > 0" />
  </header>

  <main v-bind="$attrs">
    <div v-if="state.isInitialized">
      <p>
        Rendered {{ renderCount }} times!
        <button @click="cleanse">cleanse</button>
      </p>

      <h2>Bad ducks</h2>
      <DuckList :fire-duck="fireDuck" :ducks="badDucks" showMetadata />

      <h2>Good ducks</h2>
      <DuckList :fire-duck="fireDuck" :ducks="goodDucks" />
    </div>
    <div v-else>
      <em>HOLD YER HORSES!</em>
    </div>
  </main>
</template>

<style>
body {
  margin: 0;
  padding: 0;
}
</style>
<style scoped>
header {
  margin-top: 0;
  background-color: rgb(255 277 108);
  padding: 1rem;
  position: sticky;
  top: 0;
  border-bottom: 1px solid rgb(33 33 33);
  text-align: center;
  z-index: 1000;
}

a {
  color: #42b983;
}

label {
  margin: 0 0.5em;
  font-weight: bold;
}

code {
  background-color: #eee;
  padding: 2px 4px;
  border-radius: 4px;
  color: #304455;
}
h1 {
  margin: 0;
  font-size: 30px;
}

main {
  margin: 1em;
  padding: 0;
}

img {
  vertical-align: middle;
  margin-right: 0.5em;
}
</style>

// src/components/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { DuckProspectType, DuckType } from "../services/duck";
  import duckService from "../services/duck";
  import { cleanse } from "../services/instance";
  import Spinner from "./Spinner.svelte";
  import { Router, Route } from "svelte-navigator";
  import IndexPage from "./IndexPage.svelte";
  import DuckPage from "./DuckPage.svelte";
  import mlrdLogo from "../assets/favicon.png";

  let url = "";

  let renderCount = 0;

  let ducks: Record<string, DuckType> = {};
  let isInitialized: boolean = false;
  let operationsPending = 0;

  let duckIsBeingHired = false;

  const hireDuck = async (prospect: DuckProspectType) => {
    duckIsBeingHired = true;
    operationsPending = operationsPending + 1;

    const duck = await duckService.hireDuck(prospect);

    duckIsBeingHired = false;
    ducks[duck.id] = duck;
    operationsPending = operationsPending - 1;
  };

  const fireDuck = async (id: string) => {
    operationsPending = operationsPending + 1;
    ducks[id].isBeingFired = true;
    ducks = ducks;

    const firedDuck = await duckService.fireDuck(id);
    ducks[firedDuck.id].hasbeenFired = true;
    ducks = ducks;
    operationsPending = operationsPending - 1;

    setTimeout(() => {
      delete ducks[firedDuck.id];
      ducks = ducks;
    }, 3000);

    ducks = ducks;
  };

  onMount(() => {
    const interval = setInterval(() => {
      renderCount = renderCount + 1;
    }, 1000);

    return () => {
      clearInterval(interval);
    };
  });

  onMount(async () => {
    operationsPending = operationsPending + 1;
    const dux = await duckService.getDucks();
    ducks = Object.fromEntries(dux.map((d) => [d.id, d]));
    isInitialized = true;
    operationsPending = operationsPending - 1;
  });

  $: duckList = Object.values(ducks) || [];
</script>

<svelte:head>
  <title>Mrld ERP</title>
</svelte:head>

{#if operationsPending > 0}
  <Spinner />
{/if}
<header>
  <h1>
    <img width="50px" alt="Mallard ERP" src={mlrdLogo} />Mallard ERP
  </h1>
</header>

<main>
  <p>
    I have been rendered <strong>{renderCount}</strong> times!{" "}
    <button
      type="button"
      on:click={(e) => {
        console.log(e);
        e.preventDefault();
        cleanse();
      }}
    >
      cleanse
    </button>
  </p>

  <Router {url}>
    <Route path="/">
      <IndexPage {hireDuck} {isInitialized} ducks={duckList} {fireDuck} />
    </Route>
    <Route path="/duck/:id" let:params>
      <DuckPage id={params.id.substring(1)} {ducks} />
    </Route>
  </Router>
</main>

<style>
  :root {
    font-family: "Comic Sans MS", serif;
    background-image: url("/src/assets/duckling-pattern.png");
    font-size: 18px;
    background-attachment: fixed;
    background-position: top left;
  }

  :global(body) {
    margin: 0;
    padding: 0;
  }

  main {
    margin: 1em;
    padding: 0;
  }

  header {
    margin-top: 0;
    background-color: rgb(255 277 108);
    padding: 1rem;
    position: sticky;
    top: 0;
    border-bottom: 1px solid rgb(33 33 33);
    text-align: center;
    z-index: 1000;
  }

  img {
    vertical-align: middle;
    margin-right: 0.5em;
  }

  h1 {
    margin: 0;
    font-size: 30px;
  }
</style>
