// src/components/DuckList.vue
<script setup lang="ts">
import { defineProps, computed } from 'vue'
import { DuckType, getDucks } from '../services/duck';
import Duck from "./Duck.vue";
import { sortWith, descend, ascend, prop } from "ramda";

const duckSorter = sortWith<DuckType>([
  ascend(prop("lastName")),
  ascend(prop("firstName"))
]);

const props = defineProps<{
  ducks: DuckType[];
  fireDuck: (id: string) => void;
  showMetadata?: boolean
}>()


const averageAge = computed(() => {
  return props.ducks.reduce((a, duck) => a + duck.age, 0) / props.ducks.length;
});

const sortedDucks = computed(() => duckSorter(props.ducks));

</script>

<template>
  <div v-if="ducks.length > 0">
    <p
      v-if="showMetadata"
    >Number of ducks: {{ ducks.length }}, average age: {{ averageAge.toFixed(2) }}</p>

    <ul
      v-motion
      :initial="{
        opacity: 0,
        x: -500,
      }"
      :enter="{
        opacity: 1,
        x: 0,
      }"
    >
      <li v-motion v-for="duck in sortedDucks" :duck="duck" :key="duck.id">
        <Duck :duck="duck" :fire-duck="fireDuck" />
      </li>
    </ul>
  </div>
  <div v-else>
    <p>zero ducks given!</p>
  </div>
</template>

<style>
body {
  margin: 0;
  padding: 0;
}
</style>
<style scoped>
ul {
  list-style-type: none;
  margin: 2em 0;
  padding: 0;
}

li:first-child {
  margin-top: 0;
}

li:last-child {
  margin-bottom: 0;
}
</style>

// src/components/DuckList.svelte
<script lang="ts">
  import type { DuckType } from "src/services/duck";
  import Duck from "./Duck.svelte";
  export let ducks: DuckType[];
  export let showMetadata: boolean = false;
  export let fireDuck: (id: string) => void;
  import { fly } from "svelte/transition";
  import { sortWith, descend, ascend, prop } from "ramda";

  const duckSorter = sortWith<DuckType>([
    ascend(prop("lastName")),
    ascend(prop("firstName"))
  ]);

  $: averageAge = ducks.reduce((a, d) => a + d.age, 0) / ducks.length;

  $: sortedDucks = duckSorter(ducks);
</script>

{#if ducks.length > 0}
  <ul>
    {#if showMetadata}
      <p>
        Number of ducks: {ducks.length}, average age: {averageAge.toFixed(2)}
      </p>
    {/if}

    {#each sortedDucks as duck (duck.id)}
      {#if !duck.hasbeenFired}
        <li
          in:fly={{
            delay: 250,
            duration: 300,
            x: -1000
            //opacity: 0.5
            // easing: quintOut
          }}
          out:fly|local={{
            delay: 250,
            duration: 300,
            x: 1000
          }}
        >
          <Duck {fireDuck} {duck} />
        </li>
      {/if}
    {/each}
  </ul>
{:else}
  <p>Zero ducks given.</p>
{/if}

<style>
  ul {
    list-style-type: none;
    margin: 2em 0;
    padding: 0;
  }

  li:first-child {
    margin-top: 0;
  }

  li:last-child {
    margin-bottom: 0;
  }
</style>
