// src/components/DuckList.vue
<script setup lang="ts">
import { defineProps, computed } from 'vue'
import { DuckType, getDucks } from '../services/duck';
import Duck from "./Duck.vue";
import { sortWith, descend, ascend, prop } from "ramda";

const duckSorter = sortWith<DuckType>([
  ascend(prop("lastName")),
  ascend(prop("firstName"))
]);

const props = defineProps<{
  ducks: DuckType[];
  fireDuck: (id: string) => void;
  showMetadata?: boolean
}>()


const averageAge = computed(() => {
  return props.ducks.reduce((a, duck) => a + duck.age, 0) / props.ducks.length;
});

const sortedDucks = computed(() => duckSorter(props.ducks));

</script>

<template>
  <div v-if="ducks.length > 0">
    <p
      v-if="showMetadata"
    >Number of ducks: {{ ducks.length }}, average age: {{ averageAge.toFixed(2) }}</p>

    <ul
      v-motion
      :initial="{
        opacity: 0,
        x: -500,
      }"
      :enter="{
        opacity: 1,
        x: 0,
      }"
    >
      <li v-motion v-for="duck in sortedDucks" :duck="duck" :key="duck.id">
        <Duck :duck="duck" :fire-duck="fireDuck" />
      </li>
    </ul>
  </div>
  <div v-else>
    <p>zero ducks given!</p>
  </div>
</template>

<style>
body {
  margin: 0;
  padding: 0;
}
</style>
<style scoped>
ul {
  list-style-type: none;
  margin: 2em 0;
  padding: 0;
}

li:first-child {
  margin-top: 0;
}

li:last-child {
  margin-bottom: 0;
}
</style>

// src/components/DuckList.tsx
import { memo, VFC } from "react";
import { DuckType } from "../services/duck";
import Duck from "./Duck";
import {
  motion,
  AnimatePresence,
  Variants,
  LayoutGroup,
  useReducedMotion
} from "framer-motion";
import { ascend, descend, sortWith, prop } from "ramda";

import styles from "./DuckList.module.css";

const duckSorter = sortWith<DuckType>([
  ascend(prop("lastName")),
  ascend(prop("firstName"))
]);

type Props = {
  ducks: DuckType[];
  fireDuck: (id: string) => void;
  showMetadata?: boolean;
};

const DuckList: VFC<Props> = ({ ducks, fireDuck, showMetadata = false }) => {
  const shouldReduceMotion = useReducedMotion();

  const variants: Variants = {
    initial: {
      opacity: 0,
      x: shouldReduceMotion ? 0 : "-50vh"
    },
    visible: {
      opacity: 1,
      x: 0,
      transition: {
        when: "beforeChildren",
        staggerChildren: 0.1,
        duration: 0.5
      }
    },
    hidden: {
      opacity: 0,
      transition: {
        when: "afterChildren",
        staggerChildren: 0.3
      }
    },
    exit: {
      opacity: 0,
      x: shouldReduceMotion ? 0 : "105vh",
      transition: {
        duration: 0.5
      }
    }
  };

  if (ducks.length === 0) {
    return <section>zero ducks given.</section>;
  }

  const averageAge = ducks.reduce((a, d) => a + d.age, 0) / ducks.length;

  const sortedDucks = duckSorter(ducks);

  return (
    <section>
      {showMetadata && (
        <p>
          Number of ducks: {ducks.length}, average age: {averageAge.toFixed(2)}
        </p>
      )}

      <LayoutGroup>
        <motion.ul
          className={styles.root}
          variants={variants}
          initial="initial"
          animate="visible"
        >
          <AnimatePresence>
            {sortedDucks.map((duck) => (
              <motion.li layout key={duck.id} variants={variants} exit="exit">
                <Duck fireDuck={fireDuck} duck={duck} />
              </motion.li>
            ))}
          </AnimatePresence>
        </motion.ul>
      </LayoutGroup>
    </section>
  );
};

export default memo(DuckList);
